# Generated by Django 5.1.7 on 2025-03-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerstudent',
            options={},
        ),
        migrations.AlterModelManagers(
            name='registerstudent',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='registerstudent',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='registerstudent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registerstudent',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registerstudent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registerstudent',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='registerstudent',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='registerstudent',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registerstudent',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='registerstudent',
            name='username',
        ),
    ]
