# Generated by Django 5.1.7 on 2025-04-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudents',
            name='PhoneNumber',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
