# Generated by Django 5.1.7 on 2025-04-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_registerstudents_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudents',
            name='Gender',
            field=models.CharField(max_length=6),
        ),
    ]
