# Generated by Django 5.1.7 on 2025-04-10 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('SchoolId', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('SchoolName', models.CharField(max_length=100)),
                ('Dean', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseId', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('SchoolName', models.CharField(max_length=100)),
                ('CourseInstractor', models.CharField(max_length=100)),
                ('YoutubeLink', models.URLField(editable=False, unique=True)),
                ('SchoolId', models.ForeignKey(db_column='SchoolId', on_delete=django.db.models.deletion.CASCADE, to='Schools.school')),
            ],
        ),
    ]
