# Generated by Django 5.1.7 on 2025-04-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseId', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=120)),
                ('CourseInstractor', models.CharField(max_length=100)),
                ('YoutubeLink', models.URLField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('SchoolId', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('SchoolName', models.CharField(max_length=100)),
                ('Dean', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCohort',
            fields=[
                ('CohortId', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('CohortName', models.CharField(max_length=50)),
                ('CourseId', models.ForeignKey(db_column='CourseId', on_delete=django.db.models.deletion.CASCADE, to='Schools.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liveLink', models.URLField(max_length=500)),
                ('recordedLink', models.URLField(max_length=500)),
                ('CohortId', models.ForeignKey(db_column='CohortId', on_delete=django.db.models.deletion.CASCADE, to='Schools.coursecohort')),
                ('courseId', models.ForeignKey(db_column='CourseId', on_delete=django.db.models.deletion.CASCADE, to='Schools.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='SchoolId',
            field=models.ForeignKey(db_column='SchoolId', on_delete=django.db.models.deletion.CASCADE, to='Schools.school'),
        ),
    ]
