# Generated by Django 5.1.7 on 2025-05-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0001_initial'),
    ]

    operations = [
    ]
