# Generated by Django 5.1.7 on 2025-04-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecohort',
            name='CohortStatus',
            field=models.BooleanField(default=True),
        ),
    ]
