# Generated by Django 5.1.7 on 2025-04-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0002_remove_course_schoolname_courseresources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='YoutubeLink',
            field=models.URLField(editable=False, max_length=500, unique=True),
        ),
    ]
