# Generated by Django 5.1.7 on 2025-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0003_alter_course_youtubelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='YoutubeLink',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='courseresources',
            name='live_link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='courseresources',
            name='recorded_link',
            field=models.URLField(max_length=500),
        ),
    ]
