# Generated by Django 5.1.7 on 2025-08-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_coursefee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLiveClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('YouTube', 'YouTube'), ('Zoom', 'Zoom'), ('googleMeet', 'googleMeet')], default='YouTube', max_length=50)),
                ('class_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='school.course')),
            ],
            options={
                'verbose_name': 'Course live  class',
                'verbose_name_plural': 'Course live classes',
            },
        ),
        migrations.CreateModel(
            name='CourseLiveRecordedSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('YouTube', 'YouTube'), ('PDF', 'PDF'), ('Link', 'Link')], default='YouTube', max_length=50)),
                ('resourse_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded', to='school.course')),
            ],
            options={
                'verbose_name': 'Course live recorded session',
                'verbose_name_plural': 'Course live recorded sessions',
            },
        ),
    ]
